version: '3'
services:
  app:
    build: ./app
    command: python3 app/app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7.16
    ports:
      - "52000:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
